[workspace]
authors = ["Bharath Air <bharath.ananthsub@gmail.com>"]
channels = ["conda-forge"]
name = "dsc"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[dependencies]
python = ">=3.9,<3.13"

[pypi-dependencies]
dsc = {path = ".", editable = true}
h5py = "*"
msgpack-python = "*"
numexpr = "*"
numpy = ">=1.16.2"
pandas = ">=0.24.2"
ptable = "*"
pyarrow = ">=0.5.0"
sqlalchemy = "*"
sympy = "*"
tzlocal = "*"
sos = { git = "https://github.com/vatlab/sos.git" }
sos-pbs = { git = "https://github.com/vatlab/sos-pbs.git" }

[feature.py310.dependencies]
python = "3.10.*"

[feature.py310.tasks]
test = "cd vignettes && sh test.sh"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py311.tasks]
test = "cd vignettes && sh test.sh"

[feature.py309.dependencies]
python = "3.9.*"

[environments]
py310 = ["py310"]
py311 = ["py311"]
py309 = ["py309"]

[tasks]
test = "cd vignettes && sh test.sh"
